#!/bin/bash

#PBS -P vp91
#PBS -q normal

#PBS -l ncpus=96
#PBS -l mem=10GB
#PBS -l walltime=00:05:00 

#PBS -N multinode

module load python3/3.11.0  
module load cuda/12.3.2
module load nccl/2.19.4

. /scratch/vp91/Training-Venv/pytorch/bin/activate

which python

# Get the list of allocated nodes
NODES=$(cat $PBS_NODEFILE | uniq)
echo $NODES

NODE_ARR=($NODES)
echo $NODE_ARR

# Define the master node (usually the first node in the list)
MASTER_ADDR=${NODE_ARR[0]}
MASTER_PORT=12355  # Set an appropriate port for communication
echo $MASTER_ADDR

NNODES=2
NPROC_PER_NODE=4
WORLD_SIZE=$(($NNODES * $NPROC_PER_NODE))

echo $WORLD_SIZE

echo $PBS_NODEID

# Rendezvous backend and endpoint
RDZV_BACKEND="c10d"
RDZV_ENDPOINT="${MASTER_ADDR}:${MASTER_PORT}"